package-lock.json, package.json, src/scss/abstracts/palette.scss, src/scss/components/Button.scss, src/scss/components/Dialog.scss, src/scss/components/Monogram.scss, src/scss/components/input/Blank.scss, src/scss/components/input/Input.scss, src/scss/components/input/Persistent.scss, src/scss/components/input/TextArea.scss, src/scss/utils/colors.scss, src/scss/utils/has-action.scss
**Features**
- Error Buttons
- Has Action – error variant
**Fixes**
- Dropdown height inconsistent with Input
- Dialog List Item height is inconsistent
=> Danger Buttons

package-lock.json, package.json, src/scss/components/Card.scss, src/scss/components/Dialog.scss, src/scss/components/Title.scss, src/scss/components/input/Dropdown.scss, src/scss/utils/has-action.scss
**Features**
* New Z index system
**Fixes**
* https://github.com/suankularb-wittayalai-school/sk-components/issues/33
* https://github.com/suankularb-wittayalai-school/sk-components/issues/34
**Refs**
Fixes #33, fixes #34
=> Fix: Card Has Action

package-lock.json, package.json, src/scss/components/Table.scss, src/scss/utils/_all.scss, src/scss/utils/layout-grid.scss, src/scss/utils/text-stroke.scss
**Features**
- Text Stroke utils (adds outline to text)
**Fixes**
- https://github.com/suankularb-wittayalai-school/sk-components/issues/41
- https://github.com/suankularb-wittayalai-school/sk-components/issues/42
**Refs**
Fixes #41, fixes #42
=> Text Stroke

src/scss/components/Chip.scss, src/scss/components/Icon.scss
**Features**
- Input Chip
Resolves #48
- Button Chip
Resolves #49
**Fixes**
- Icon has no fixed height (just in case)
=> Input Chip and Icon Chip

src/scss/components/Card.scss, src/scss/components/Navigation.scss, src/scss/components/Title.scss, src/scss/components/input/Blank.scss, src/scss/components/input/Dropdown.scss, src/scss/components/input/File.scss, src/scss/components/input/Input.scss, src/scss/components/input/Persistent.scss, src/scss/layouts/Page.scss, src/scss/layouts/Regular.scss
**Features**
- Transparent Navigation
- Error indicator (red line) in Input
- Error message (red text) in Input
- Helper message (gray text) in Input
**Fixes**
- Title has too much line-height on desktop
- Subtitle in Title should be light
- Dropdown Options is behind Label
=> Transparent Navigation and Input Overhaul

src/scss/abstracts/palette.scss, src/scss/components/Button.scss, src/scss/utils/disabled.scss
**Features**
- Disabled Buttons
- Filled/tonal (Disabled versions are the same)
- Outlined
- Text
- Disabled util
=> Disabled Buttons

src/scss/components/Dialog.scss
**Fixes**
- Dialog Columns gap can be adjusted for Input
=> Hotifx: Dialog Columns Adjustable Gap

package-lock.json, src/scss/abstracts/typography.scss, src/scss/components/Button.scss, src/scss/components/Card.scss, src/scss/components/Chip.scss, src/scss/components/Dialog.scss, src/scss/components/Icon.scss, src/scss/components/Navigation.scss, src/scss/components/Title.scss, src/scss/components/XScrollContent.scss, src/scss/layouts/Page.scss, src/scss/layouts/Regular.scss
**Features**
- Migration to Material Symbols
- Scroll snapping in X Scroll Content
**Fixes**
- iOS compatibility
Fixes #60 (probably)
- Chip List has contrast issues when placed in Dialog
**Notes**
It is impossible to test this pull request the way I usually test because Apple. We literally won’t know if this will work until we actually use these in a project.
=> Refactor: iOS Compatibility

src/scss/components/Actions.scss, src/scss/components/Banner.scss, src/scss/components/Card.scss, src/scss/components/Chip.scss, src/scss/components/Icon.scss, src/scss/components/Navigation.scss, src/scss/components/Noticebar.scss, src/scss/components/Table.scss, src/scss/components/Title.scss, src/scss/components/_all.scss, src/scss/layouts/List.scss, src/scss/layouts/Page.scss, src/scss/layouts/Regular.scss
<table>
<tr>
<td>
</td>
<td>
</td>
<tr>
</table>
**Features**
- Actions
- Banner
Resolves #64
- Noticebar
Resolves #62
- Fixed Title is now opt-in, the default is Title scrolls with the page
**Fixes**
- Main Section does not behave like Regular Layout
Fixes #56
- Table lacks scrollbar on desktop
- Selected Chip’s state layer doesn’t fully cover the Chip
=> Banner and Noticebar

apps/storybook/stories/Checklist.stories.tsx, apps/storybook/stories/DataTable.stories.tsx, package-lock.json, package.json, packages/skcom-react/package.json, packages/skcom-react/src/components/DataTable/DataTable.tsx, packages/skcom-react/src/components/DataTable/index.ts, packages/skcom-react/src/components/Table/Table.tsx, packages/skcom-react/src/components/index.ts, packages/skcom-react/src/index.ts
=> Data Table

.gitattributes, .github/actions/nodejs-ci.yml
**Fixes**
- Missing GitHub configuration files
=> Hotfix: Missing GitHub Config Files

README.md
**Features**
- Readme file
Resolves #40
=> [3.0] Readme File

packages/skcom-css/package.json, packages/skcom-react/package.json
**Fixes**
- `dist` folder isn’t published to NPM for both SKCom Styles and ReSKCom
=> [3.0.3] Hotfix: `dist` Folder not Published

apps/demo/components/Layout.tsx, apps/demo/components/PageHeader.tsx, apps/demo/contexts/NavDrawerContext.tsx, apps/demo/next.config.js, apps/demo/package.json, apps/demo/pages/_app.tsx, apps/demo/pages/components/actions.tsx, apps/demo/pages/components/communication.tsx, apps/demo/pages/components/containers.tsx, apps/demo/pages/components/index.tsx, apps/demo/pages/components/input.tsx, apps/demo/pages/example/index.tsx, apps/demo/pages/example/lookup/details.tsx, apps/demo/pages/example/lookup/index.tsx, apps/demo/pages/index.tsx, apps/demo/utils/types.ts, package-lock.json, packages/skcom-css/src/components/split-layout.scss, packages/skcom-react/package.json, packages/skcom-react/src/components/ContentLayout/index.tsx, packages/skcom-react/src/components/FAB/index.tsx, packages/skcom-react/src/components/NavBar/index.tsx, packages/skcom-react/src/components/PageHeader/index.tsx, packages/skcom-react/src/components/RootLayout/index.tsx, packages/skcom-react/tsup.config.ts
**Fixes**
- Buggy page transitions (temporarily fixed by removing page transitions)
- The demo application does not replicate the one real-world usage of SKCom: MySK
- Causes layout shift by Progress when the page is loading
- FAB has no animation when minimizing
- The list side of Split Layout has weird scroll behaviour on mobile
=> [3.0.4] Fix: Progress Layout Shift

apps/demo/pages/components/containers.tsx, packages/skcom-css/src/components/table-cell.scss, packages/skcom-css/src/components/table-row.scss, packages/skcom-react/src/components/DataTable/index.tsx, packages/skcom-react/src/components/DataTableBody/index.tsx, packages/skcom-react/src/components/TableRow/index.tsx
**Features**
- Row actions
- Layout animation for Data Table is now opt-in
=> [3.0.4] Row actions

apps/demo/package.json, package-lock.json, packages/skcom-css/src/components/table-cell.scss, packages/skcom-css/src/components/table-row.scss, packages/skcom-react/package.json, packages/skcom-react/src/components/DataTable/index.tsx, packages/skcom-react/src/components/TableRow/index.tsx
**Fixes**
- Row actions is incompatible with Safari and in effect iOS devices;
`position: relative` cannot be applied to `<tr>`
- `layout` prop of Data Table should be optional
- ReSKCom peer dependencies may be incompatible with Next.js 13.4
=> [3.1.0] Row Actions on Safari

apps/demo/components/Layout.tsx, apps/demo/components/example/lookup/ShareDialog.tsx, apps/demo/components/example/lookup/StudentDetails.tsx, apps/demo/package.json, apps/demo/pages/404.tsx, apps/demo/pages/components/containers.tsx, apps/demo/pages/example/index.tsx, apps/demo/pages/example/lookup/index.tsx, apps/demo/pages/index.tsx, package-lock.json, packages/skcom-css/package.json, packages/skcom-css/src/abstracts/abstracts.scss, packages/skcom-css/src/components/button.scss, packages/skcom-css/src/components/text.scss, packages/skcom-react/package.json, packages/skcom-react/src/components/AssistChip/index.tsx, packages/skcom-react/src/components/Button/index.tsx, packages/skcom-react/src/components/ChipField/index.tsx, packages/skcom-react/src/components/DataTableHead/index.tsx, packages/skcom-react/src/components/FilterChip/index.tsx, packages/skcom-react/src/components/InputChip/index.tsx, packages/skcom-react/src/components/SuggestionChip/index.tsx, packages/skcom-react/src/components/Text/index.tsx, packages/skcom-react/src/components/TextField/index.tsx, packages/skcom-react/src/index.tsx, packages/skcom-react/src/utils/animation.ts
**Features**
- Text component
**Fixes**
- Chips and Button, when not supplied with `onClick`, `href`, or `element`, defaults to `<div>`
=> [3.2.0] Text Component

packages/skcom-react/src/components/Progress/index.tsx, packages/skcom-react/vite.config.ts
**Fixes**
- Circular Progress value not updating
=> Release 3.2.3 (Hotfix)

apps/demo/package.json, package-lock.json, package.json, packages/configs/package.json, packages/skcom-css/package.json, packages/skcom-css/src/components/progress.scss, packages/skcom-react/package.json, packages/skcom-react/src/components/Progress/index.tsx, packages/skcom-react/src/utils/animation.ts
**Features**
- Matched Progress to new Material Design specifications
- Increased ReSKCom dev server heap size to decrease the frequency of crashes
**Fixes**
- Incorrect values in `useAnimationConfig`
Fixes #127
=> [3.3.0] New Progress

packages/skcom-css/src/abstracts/_palette.scss, packages/skcom-css/src/components/_chip.scss, packages/skcom-css/src/components/avatar.scss, packages/skcom-css/src/components/input-chip.scss, packages/skcom-css/src/components/menu-item.scss, packages/skcom-css/src/components/nav-bar-item.scss, packages/skcom-css/src/components/progress.scss, packages/skcom-css/src/components/toggle-button.scss, packages/skcom-react/src/components/Button/index.tsx, packages/skcom-react/src/components/PageHeader/FixedBackgroundBlobs.tsx
**Features**
- Contrast modes adaptations
**Fixes**
- Contrast palettes were not applied
- Button loses width while loading
Fixes FRO-75
- Selected Menu Item background was not applied
- Selected Nav Bar Item color did not match Material specs
- `FixedBackgroundBlobs` props caused warnings
**Notes**
Resolves FRO-76
=> Release 3.3.1
